### ISSUE TITLE
你好，请问onlineSPC_Data是sql server数据库文件吗，我安装了sql server，然后手动创建了onlineSPC数据库，运行程序可以提出登录页面，输入admin admin就报错了

### ISSUE THREAD

**Issue by LDS13590023880** [liyonghuan/online-statistical-process-control-system#1]
你好，请问onlineSPC_Data是sql server数据库文件吗，我安装了sql server，然后手动创建了onlineSPC数据库，运行程序可以弹出登录页面，输入admin admin就报错了，我自己新建的数据库的空的，是不是里面要导入数据才行？

**Comment by eyuan** [comment]
> 你好，请问onlineSPC_Data是sql server数据库文件吗，我安装了sql server，然后手动创建了onlineSPC数据库，运行程序可以弹出登录页面，输入admin admin就报错了，我自己新建的数据库的空的，是不是里面要导入数据才行？

你的数据库哪里来的？我没找到建库的SQL，帮忙指点迷津下吧

**Comment by liyonghuan** [comment]
> 你好，请问onlineSPC_Data是sql server数据库文件吗，我安装了sql server，然后手动创建了onlineSPC数据库，运行程序可以弹出登录页面，输入admin admin就报错了，我自己新建的数据库的空的，是不是里面要导入数据才行？

是的，需要通过还原的方式把这份数据库文件导入sql server。

**Comment by liyonghuan** [comment]
> > 你好，请问onlineSPC_Data是sql server数据库文件吗，我安装了sql server，然后手动创建了onlineSPC数据库，运行程序可以弹出登录页面，输入admin admin就报错了，我自己新建的数据库的空的，是不是里面要导入数据才行？
> 
> 你的数据库哪里来的？我没找到建库的SQL，帮忙指点迷津下吧

数据就是onlineSPC_Data这个文件。
