### ISSUE TITLE
你这个有数据库文件吗

### ISSUE THREAD

**Issue by tuohaibei** [liyonghuan/online-statistical-process-control-system#3]
你这个有数据库文件吗

**Comment by liyonghuan** [comment]
[onlineSPC_Data](https://github.com/liyonghuan/online-statistical-process-control-system/blob/master/onlineSPC_Data)

**Comment by W050697** [comment]
> [onlineSPC_Data](https://github.com/liyonghuan/online-statistical-process-control-system/blob/master/onlineSPC_Data)
> 
> [onlineSPC_Data](https://github.com/liyonghuan/online-statistical-process-control-system/blob/master/onlineSPC_Data)

这个文件什么格式

**Comment by liyonghuan** [comment]
> > [onlineSPC_Data](https://github.com/liyonghuan/online-statistical-process-control-system/blob/master/onlineSPC_Data)
> > [onlineSPC_Data](https://github.com/liyonghuan/online-statistical-process-control-system/blob/master/onlineSPC_Data)
> 
> 这个文件什么格式

没有格式，通过数据库还原的方式就可以把这个数据库数据恢复了。

**Comment by W050697** [comment]
以解决，感谢



***@***.***
 
发件人： 理幻
发送时间： 2024-07-15 14:14
收件人： liyonghuan/online-statistical-process-control-system
抄送： Miaowj; Comment
主题： Re: [liyonghuan/online-statistical-process-control-system] 你这个有数据库文件吗 (Issue #3)
onlineSPC_Data
onlineSPC_Data
这个文件什么格式
没有格式，通过数据库还原的方式就可以把这个数据库数据恢复了。
